// front_end/src/App.vue
<template>
  <v-app :style="{ backgroundColor: $vuetify.theme.current.colors.background }">
    <v-main class="live2d-main">
      <div class="live2d-stage">
        <Live2DViewer
          ref="live2dViewer"
          :model-path="currentModelPath"
          :motions="motions"
          :expressions="expressions"
          :width="viewerWidth"
          :height="viewerHeight"
          @model-loaded="handleModelLoaded"
          @model-error="handleModelError"
          class="live2d-canvas"
        />
        <v-btn
          class="config-toggle"
          icon="mdi-tune-variant"
          variant="tonal"
          color="primary"
          @click="showConfigPanel = true"
        ></v-btn>
        <v-btn
          class="mic-toggle"
          :icon="isRecording ? 'mdi-microphone-off' : 'mdi-microphone'"
          variant="tonal"
          :color="isRecording ? 'error' : 'primary'"
          @click="toggleMicrophone"
        ></v-btn>
        <v-btn
          class="text-toggle"
          icon="mdi-pencil"
          variant="tonal"
          color="primary"
          @click="openTextInputDialog"
        ></v-btn>
        <SubtitleBar :text="subtitleText" />
      </div>

      <v-dialog v-model="showConfigPanel" max-width="480" persistent scrollable>
        <v-card class="config-dialog">
          <v-toolbar flat density="comfortable">
            <v-btn icon="mdi-close" variant="text" @click="showConfigPanel = false"></v-btn>
            <v-toolbar-title>Live2D 控制面板</v-toolbar-title>
            <v-spacer></v-spacer>
            <v-chip
              v-if="modelLoaded"
              density="compact"
              color="success"
              variant="tonal"
              prepend-icon="mdi-check-circle"
            >
              模型已加载
            </v-chip>
          </v-toolbar>
          <v-divider></v-divider>
          <v-card-text class="config-dialog__body">
            <Live2DControls
              :live2d-viewer="live2dViewer"
              :model-loaded="modelLoaded"
              @model-change="handleModelChange"
              @motions-update="handleMotionsUpdate"
              @expressions-update="handleExpressionsUpdate"
              @auto-eye-blink-change="handleAutoEyeBlinkChange"
              @auto-breath-change="handleAutoBreathChange"
              @eye-tracking-change="handleEyeTrackingChange"
              @model-scale-change="handleModelScaleChange"
              @background-change="handleBackgroundChange"
              class="config-dialog__controls"
            />
          </v-card-text>
        </v-card>
      </v-dialog>

      <v-dialog v-model="showTextInputDialog" max-width="420">
        <v-card>
          <v-card-title class="text-h6">发送文字消息</v-card-title>
          <v-card-text>
            <v-textarea
              v-model="textInputContent"
              auto-grow
              rows="3"
              counter
              maxlength="400"
              :disabled="isSendingText"
              placeholder="输入你想让她说的话..."
              @keydown.enter.prevent="submitTextInput"
            />
            <v-alert
              v-if="textInputError"
              type="error"
              variant="tonal"
              density="comfortable"
              class="mt-2"
            >
              {{ textInputError }}
            </v-alert>
          </v-card-text>
          <v-card-actions class="justify-end">
            <v-btn variant="text" @click="closeTextInputDialog" :disabled="isSendingText">取消</v-btn>
            <v-btn color="primary" :loading="isSendingText" @click="submitTextInput">发送</v-btn>
          </v-card-actions>
        </v-card>
      </v-dialog>
    </v-main>
  </v-app>
</template>

<script setup>
import { ref, watch, onBeforeUnmount } from 'vue';
import Live2DViewer from './components/Live2DViewer.vue';
import Live2DControls from './components/Live2DControls.vue';
import SubtitleBar from './components/SubtitleBar.vue';
import { useApi } from './composables/useApi';
import { useStreamingChat } from './composables/useStreamingChat';
import { useSubtitleFeed } from './composables/useSubtitleFeed';

const live2dViewer = ref(null);
const modelLoaded = ref(false);
const currentModelPath = ref('/src/live2d/models/Haru/Haru.model3.json');
const showConfigPanel = ref(false);
const motions = ref([]);
const expressions = ref([]);
const { subtitleText, appendDelta, replaceText, clearSubtitle, beginStream } = useSubtitleFeed();
const viewerWidth = ref(400);
const viewerHeight = ref(600);
const showTextInputDialog = ref(false);
const textInputContent = ref('');
const textInputError = ref('');
const isSendingText = ref(false);

const { receivedAudioUrl, isRecording, startRecording, stopRecording, recordingError } = useApi();
const { startStreaming, cancelStreaming, onDelta, onDone, onError } = useStreamingChat();

const detachDelta = onDelta((delta) => {
  appendDelta(delta);
});

const detachDone = onDone(() => {
  replaceText(subtitleText.value);
});

const detachError = onError((error) => {
  console.error('字幕流式输出发生错误:', error);
  clearSubtitle();
});

const handleModelLoaded = (model) => {
  modelLoaded.value = true;
  if (live2dViewer.value?.initAudioContext) {
    live2dViewer.value.initAudioContext();
  }
};

const handleModelError = (error) => {
  modelLoaded.value = false;
  console.error('Model error in App:', error);
};

const handleModelChange = (newModelPath) => {
  currentModelPath.value = newModelPath;
  modelLoaded.value = false;
};

const handleMotionsUpdate = (updatedMotions) => {
  motions.value = updatedMotions;
};

const handleExpressionsUpdate = (updatedExpressions) => {
  expressions.value = updatedExpressions;
};

const handleAutoEyeBlinkChange = (enabled) => {
  const manager = live2dViewer.value?.getManager?.();
  manager?.setAutoEyeBlinkEnable(enabled);
};

const handleAutoBreathChange = (enabled) => {
  const manager = live2dViewer.value?.getManager?.();
  manager?.setAutoBreathEnable(enabled);
};

const handleEyeTrackingChange = (enabled) => {
  const manager = live2dViewer.value?.getManager?.();
  manager?.setEyeTrackingEnable(enabled);
};

const handleModelScaleChange = (scale) => {
  const manager = live2dViewer.value?.getManager?.();
  manager?.setModelScale(scale);
};

const handleBackgroundChange = (backgroundConfig) => {
  const manager = live2dViewer.value?.getManager?.();
  manager?.setBackground(
    backgroundConfig.image,
    backgroundConfig.opacity,
    backgroundConfig.hasBackground,
  );
};

watch(receivedAudioUrl, (newUrl) => {
  if (newUrl && live2dViewer.value) {
    live2dViewer.value.playAudioWithLipSync(null, newUrl);
  }
});

watch(recordingError, (error) => {
  if (error) {
    console.error('录音发生错误:', error);
  }
});

const openTextInputDialog = () => {
  textInputContent.value = '';
  textInputError.value = '';
  showTextInputDialog.value = true;
};

const closeTextInputDialog = () => {
  if (isSendingText.value) return;
  showTextInputDialog.value = false;
  textInputContent.value = '';
  textInputError.value = '';
};

const submitTextInput = async () => {
  const content = textInputContent.value.trim();
  if (!content) {
    textInputError.value = '请输入要发送的内容。';
    return;
  }
  textInputError.value = '';
  isSendingText.value = true;
  try {
    await sendUserText(content, { sessionId: 'text-dialog' });
    showTextInputDialog.value = false;
    textInputContent.value = '';
  } catch (error) {
    console.error('发送文字消息失败:', error);
    textInputError.value = '发送失败，请稍后重试。';
  } finally {
    isSendingText.value = false;
  }
};

const sendUserText = async (content, options = {}) => {
  if (!content) return;
  beginStream();
  await startStreaming(options.sessionId || 'default', content, options.payload);
};

const stopStreaming = () => {
  cancelStreaming();
};

const toggleMicrophone = () => {
  if (isRecording.value) {
    stopRecording();
  } else {
    startRecording();
  }
};

onBeforeUnmount(() => {
  stopStreaming();
  detachDelta?.();
  detachDone?.();
  detachError?.();
});

// 暴露给外部以便后续集成语音识别或其他输入方式触发字幕流
defineExpose({
  sendUserText,
  stopStreaming,
});
</script>

<style scoped>
.live2d-main {
  min-height: 100vh;
  padding: 0;
  display: flex;
  align-items: stretch;
  justify-content: center;
  background: radial-gradient(circle at top, rgba(255, 255, 255, 0.4), rgba(255, 255, 255, 0));
}

.live2d-stage {
  position: relative;
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  overflow: hidden;
}

.live2d-canvas {
  width: 100%;
  height: 100%;
}

.config-toggle {
  position: absolute;
  top: 20px;
  right: 20px;
  z-index: 5;
}

.mic-toggle {
  position: absolute;
  top: 20px;
  right: 80px;
  z-index: 5;
}

.text-toggle {
  position: absolute;
  bottom: 24px;
  right: 24px;
  z-index: 6;
}

.config-dialog {
  max-height: 80vh;
  display: flex;
  flex-direction: column;
}

.config-dialog__body {
  padding: 0;
  overflow: auto;
}

.config-dialog__controls {
  min-height: 480px;
}
</style>

// front_end/src/App.jsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  Alert,
  Box,
  Button,
  Chip,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  Divider,
  IconButton,
  Stack,
  TextField,
  Typography,
} from '@mui/material';
import TuneIcon from '@mui/icons-material/Tune';
import EditIcon from '@mui/icons-material/Edit';
import CloseIcon from '@mui/icons-material/Close';
import SwapHorizIcon from '@mui/icons-material/SwapHoriz';
import Live2DViewer from './components/live2d/Live2DViewer.jsx';
import Live2DControls from './components/controls/Live2DControls.jsx';
import SubtitleBar from './components/subtitle/SubtitleBar.jsx';
import { useStreamingChat } from './hooks/useStreamingChat.js';
import { useSubtitleFeed } from './hooks/useSubtitleFeed.js';
import { desktopBridge } from './services/desktopBridge.js';

const DEFAULT_MODEL = '/live2d/models/Haru/Haru.model3.json';
const MODE_WINDOW = 'window';
const MODE_PET = 'pet';

const defaultOpenClawSettings = {
  baseUrl: '',
  token: '',
  agentId: 'main',
  hasToken: false,
  hasSecureStorage: true,
};

function normalizeErrorMessage(error) {
  if (!error) {
    return '请求失败，请稍后重试。';
  }

  if (typeof error === 'string') {
    return error;
  }

  if (typeof error?.message === 'string' && error.message) {
    return error.message;
  }

  if (typeof error?.payload?.message === 'string' && error.payload.message) {
    return error.payload.message;
  }

  return '请求失败，请稍后重试。';
}

export default function App() {
  const live2dViewerRef = useRef(null);
  const subtitleTextRef = useRef('');
  const desktopMode = desktopBridge.isDesktop();

  const [modelLoaded, setModelLoaded] = useState(false);
  const [currentModelPath, setCurrentModelPath] = useState(DEFAULT_MODEL);
  const [motions, setMotions] = useState([]);
  const [expressions, setExpressions] = useState([]);
  const [windowMode, setWindowMode] = useState(MODE_WINDOW);

  const [showConfigPanel, setShowConfigPanel] = useState(false);
  const [showTextInputDialog, setShowTextInputDialog] = useState(false);
  const [textInputContent, setTextInputContent] = useState('');
  const [textInputError, setTextInputError] = useState('');

  const [openClawSettings, setOpenClawSettings] = useState(defaultOpenClawSettings);
  const [settingsSaving, setSettingsSaving] = useState(false);
  const [settingsTesting, setSettingsTesting] = useState(false);
  const [settingsFeedback, setSettingsFeedback] = useState('');
  const [settingsError, setSettingsError] = useState('');

  const { subtitleText, appendDelta, replaceText, clearSubtitle, beginStream } = useSubtitleFeed();
  const { startStreaming, cancelStreaming, onDelta, onDone, onError, isStreaming } = useStreamingChat();

  const handleModelLoaded = useCallback(() => {
    setModelLoaded(true);
    live2dViewerRef.current?.initAudioContext?.();
  }, []);

  const handleModelError = useCallback((error) => {
    setModelLoaded(false);
    console.error('Model error in App:', error);
  }, []);

  useEffect(() => {
    let mounted = true;

    const loadSettings = async () => {
      try {
        const settings = await desktopBridge.settings.get();
        if (!mounted) {
          return;
        }

        setOpenClawSettings({
          ...defaultOpenClawSettings,
          ...settings,
        });
      } catch (error) {
        console.error('Failed to load OpenClaw settings:', error);
      }
    };

    void loadSettings();

    return () => {
      mounted = false;
    };
  }, []);

  useEffect(() => {
    subtitleTextRef.current = subtitleText;
  }, [subtitleText]);

  useEffect(() => {
    const detachDelta = onDelta((delta) => appendDelta(delta));
    const detachDone = onDone(() => replaceText(subtitleTextRef.current));
    const detachError = onError((error) => {
      console.error('字幕流式输出发生错误:', error);
      clearSubtitle();
      setTextInputError(normalizeErrorMessage(error));
    });

    return () => {
      detachDelta?.();
      detachDone?.();
      detachError?.();
    };
  }, [appendDelta, clearSubtitle, onDelta, onDone, onError, replaceText]);

  useEffect(() => {
    return () => {
      void cancelStreaming();
    };
  }, [cancelStreaming]);

  useEffect(() => {
    if (!desktopMode) {
      return undefined;
    }

    let mounted = true;

    const loadCurrentMode = async () => {
      try {
        const result = await desktopBridge.mode.getCurrent();
        if (!mounted) {
          return;
        }

        const nextMode = result?.mode === MODE_PET ? MODE_PET : MODE_WINDOW;
        setWindowMode(nextMode);
      } catch (error) {
        console.error('Failed to load current window mode:', error);
      }
    };

    const detachPreChanged = desktopBridge.mode.onPreChanged((nextMode) => {
      const targetMode = nextMode === MODE_PET ? MODE_PET : MODE_WINDOW;
      setWindowMode(targetMode);
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          desktopBridge.mode.notifyRendererReady(targetMode);
        });
      });
    });

    const detachModeChanged = desktopBridge.mode.onChanged((nextMode) => {
      const targetMode = nextMode === MODE_PET ? MODE_PET : MODE_WINDOW;
      setWindowMode(targetMode);
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          desktopBridge.mode.notifyModeRendered(targetMode);
        });
      });
    });

    void loadCurrentMode();

    return () => {
      mounted = false;
      detachPreChanged?.();
      detachModeChanged?.();
    };
  }, [desktopMode]);

  const sendUserText = useCallback(
    async (content, options = {}) => {
      if (!content) return;
      beginStream();
      await startStreaming(options.sessionId || 'default', content, options.payload);
    },
    [beginStream, startStreaming],
  );

  const stopStreaming = useCallback(() => {
    void cancelStreaming();
  }, [cancelStreaming]);

  const isPetMode = windowMode === MODE_PET;

  const setDesktopWindowMode = useCallback(
    async (nextMode) => {
      if (nextMode !== MODE_WINDOW && nextMode !== MODE_PET) {
        return;
      }

      if (!desktopMode) {
        return;
      }

      try {
        await desktopBridge.mode.set(nextMode);
      } catch (error) {
        console.error('Failed to switch window mode:', error);
      }
    },
    [desktopMode],
  );

  const bindPetHover = useCallback(
    (componentId) => {
      if (!desktopMode || !isPetMode) {
        return {};
      }

      return {
        onMouseEnter: () => desktopBridge.mode.updateHover(componentId, true),
        onMouseLeave: () => desktopBridge.mode.updateHover(componentId, false),
      };
    },
    [desktopMode, isPetMode],
  );

  const openTextInputDialog = useCallback(() => {
    setTextInputContent('');
    setTextInputError('');
    setShowTextInputDialog(true);
  }, []);

  const closeTextInputDialog = useCallback(() => {
    if (isStreaming) return;
    setShowTextInputDialog(false);
    setTextInputContent('');
    setTextInputError('');
  }, [isStreaming]);

  const submitTextInput = useCallback(async () => {
    const content = textInputContent.trim();
    if (!content) {
      setTextInputError('请输入要发送的内容。');
      return;
    }

    setTextInputError('');

    try {
      await sendUserText(content, { sessionId: 'text-dialog' });
      setShowTextInputDialog(false);
      setTextInputContent('');
    } catch (error) {
      console.error('发送文字消息失败:', error);
      setTextInputError(normalizeErrorMessage(error));
    }
  }, [sendUserText, textInputContent]);

  const stageStyle = useMemo(
    () => ({
      height: '100dvh',
      minHeight: '100dvh',
      background:
        isPetMode
          ? 'transparent'
          : 'radial-gradient(circle at top, rgba(255, 255, 255, 0.4), rgba(255, 255, 255, 0.06)), linear-gradient(180deg, #e5eeff 0%, #f9fbff 100%)',
    }),
    [isPetMode],
  );

  const handleControlModelChange = useCallback((modelPath) => {
    setCurrentModelPath(modelPath);
    setModelLoaded(false);
  }, []);

  const handleOpenClawSettingChange = useCallback((field, value) => {
    setOpenClawSettings((prev) => ({
      ...prev,
      [field]: value,
    }));
    setSettingsFeedback('');
    setSettingsError('');
  }, []);

  const saveOpenClawSettings = useCallback(async () => {
    setSettingsSaving(true);
    setSettingsError('');
    setSettingsFeedback('');

    try {
      const payload = {
        baseUrl: openClawSettings.baseUrl,
        agentId: openClawSettings.agentId,
      };
      const token = openClawSettings.token.trim();
      if (token) {
        payload.token = token;
      }

      const saved = await desktopBridge.settings.save(payload);
      setOpenClawSettings({
        ...defaultOpenClawSettings,
        ...saved,
      });
      setSettingsFeedback('OpenClaw 配置已保存。');
    } catch (error) {
      console.error('Save OpenClaw settings failed:', error);
      setSettingsError(normalizeErrorMessage(error));
    } finally {
      setSettingsSaving(false);
    }
  }, [openClawSettings.agentId, openClawSettings.baseUrl, openClawSettings.token]);

  const testOpenClawSettings = useCallback(async () => {
    setSettingsTesting(true);
    setSettingsError('');
    setSettingsFeedback('');

    try {
      const payload = {
        baseUrl: openClawSettings.baseUrl,
        agentId: openClawSettings.agentId,
      };
      const token = openClawSettings.token.trim();
      if (token) {
        payload.token = token;
      }

      const result = await desktopBridge.settings.testConnection(payload);
      if (!result?.ok) {
        setSettingsError(normalizeErrorMessage(result?.error));
      } else {
        const latency = typeof result.latencyMs === 'number' ? `（${result.latencyMs}ms）` : '';
        setSettingsFeedback(`OpenClaw 连接成功${latency}`);
      }
    } catch (error) {
      console.error('Test OpenClaw settings failed:', error);
      setSettingsError(normalizeErrorMessage(error));
    } finally {
      setSettingsTesting(false);
    }
  }, [openClawSettings.agentId, openClawSettings.baseUrl, openClawSettings.token]);

  const clearSavedToken = useCallback(async () => {
    setSettingsSaving(true);
    setSettingsError('');
    setSettingsFeedback('');

    try {
      const saved = await desktopBridge.settings.save({ clearToken: true });
      setOpenClawSettings((prev) => ({
        ...prev,
        ...saved,
        token: '',
      }));
      setSettingsFeedback('已清除保存的 Token。');
    } catch (error) {
      console.error('Clear token failed:', error);
      setSettingsError(normalizeErrorMessage(error));
    } finally {
      setSettingsSaving(false);
    }
  }, []);

  useEffect(() => {
    if (!isPetMode) {
      return;
    }

    setShowConfigPanel(false);
    setShowTextInputDialog(false);
  }, [isPetMode]);

  return (
    <Box sx={stageStyle}>
      <Box className={`live2d-stage ${isPetMode ? 'pet-mode' : 'window-mode'}`}>
        <Box className="live2d-hitbox" {...bindPetHover('live2d-hitbox')}>
          <Live2DViewer
            ref={live2dViewerRef}
            modelPath={currentModelPath}
            motions={motions}
            expressions={expressions}
            width={400}
            height={600}
            onModelLoaded={handleModelLoaded}
            onModelError={handleModelError}
            className="live2d-viewer"
          />
        </Box>

        {!isPetMode && (
          <IconButton className="config-toggle" color="primary" onClick={() => setShowConfigPanel(true)}>
            <TuneIcon />
          </IconButton>
        )}

        {!isPetMode && (
          <IconButton className="text-toggle" color="primary" onClick={openTextInputDialog}>
            <EditIcon />
          </IconButton>
        )}

        {desktopMode && !isPetMode && (
          <IconButton
            className="mode-toggle"
            color="primary"
            onClick={() => {
              void setDesktopWindowMode(MODE_PET);
            }}
            title="切换到桌宠模式"
          >
            <SwapHorizIcon />
          </IconButton>
        )}

        {desktopMode && isPetMode && (
          <Box className="pet-mode-toggle-wrap" {...bindPetHover('pet-mode-toggle-wrap')}>
            <IconButton
              className="pet-mode-toggle"
              color="primary"
              onClick={() => {
                void setDesktopWindowMode(MODE_WINDOW);
              }}
              title="切换到主窗口模式"
            >
              <SwapHorizIcon />
            </IconButton>
          </Box>
        )}

        <SubtitleBar text={subtitleText} />
      </Box>

      <Dialog
        open={showConfigPanel && !isPetMode}
        onClose={() => setShowConfigPanel(false)}
        maxWidth="sm"
        fullWidth
        keepMounted
      >
        <DialogTitle>
          <Stack direction="row" spacing={1} alignItems="center">
            <IconButton onClick={() => setShowConfigPanel(false)}>
              <CloseIcon />
            </IconButton>
            <span>Live2D 控制面板</span>
            {modelLoaded && <Chip color="success" size="small" label="模型已加载" />}
          </Stack>
        </DialogTitle>
        <DialogContent dividers>
          <Stack spacing={3}>
            <Live2DControls
              live2dViewerRef={live2dViewerRef}
              modelLoaded={modelLoaded}
              onModelChange={handleControlModelChange}
              onMotionsUpdate={setMotions}
              onExpressionsUpdate={setExpressions}
              onAutoEyeBlinkChange={(enabled) => {
                live2dViewerRef.current?.getManager?.()?.setAutoEyeBlinkEnable(enabled);
              }}
              onAutoBreathChange={(enabled) => {
                live2dViewerRef.current?.getManager?.()?.setAutoBreathEnable(enabled);
              }}
              onEyeTrackingChange={(enabled) => {
                live2dViewerRef.current?.getManager?.()?.setEyeTracking(enabled);
              }}
              onModelScaleChange={(scale) => {
                live2dViewerRef.current?.getManager?.()?.setModelScale(scale);
              }}
              onBackgroundChange={(backgroundConfig) => {
                const manager = live2dViewerRef.current?.getManager?.();
                if (!manager) return;
                if (!backgroundConfig.hasBackground) {
                  manager.clearBackground();
                  return;
                }
                manager.setBackgroundOpacity(backgroundConfig.opacity ?? 1);
              }}
            />

            <Divider />

            <Stack spacing={2}>
              <Typography variant="h6">OpenClaw 设置</Typography>

              {!desktopMode && (
                <Alert severity="warning">
                  当前为 Web 模式，Token 会存入浏览器本地存储，仅建议用于开发测试。
                </Alert>
              )}

              {desktopMode && !openClawSettings.hasSecureStorage && (
                <Alert severity="warning">系统密钥链不可用，Token 将回退为本地明文存储。</Alert>
              )}

              <TextField
                label="OpenClaw Base URL"
                value={openClawSettings.baseUrl}
                onChange={(event) => handleOpenClawSettingChange('baseUrl', event.target.value)}
                placeholder="http://127.0.0.1:18789"
                fullWidth
              />

              <TextField
                label="OpenClaw Token"
                value={openClawSettings.token}
                onChange={(event) => handleOpenClawSettingChange('token', event.target.value)}
                type="password"
                autoComplete="off"
                placeholder={openClawSettings.hasToken ? '已保存（留空表示不修改）' : ''}
                fullWidth
              />

              <TextField
                label="OpenClaw Agent ID"
                value={openClawSettings.agentId}
                onChange={(event) => handleOpenClawSettingChange('agentId', event.target.value)}
                placeholder="main"
                fullWidth
              />

              <Stack direction="row" spacing={1}>
                <Button variant="contained" onClick={saveOpenClawSettings} disabled={settingsSaving || settingsTesting}>
                  {settingsSaving ? '保存中...' : '保存设置'}
                </Button>
                <Button variant="outlined" onClick={testOpenClawSettings} disabled={settingsSaving || settingsTesting}>
                  {settingsTesting ? '测试中...' : '连接测试'}
                </Button>
                <Button
                  variant="text"
                  color="warning"
                  onClick={clearSavedToken}
                  disabled={settingsSaving || settingsTesting || !openClawSettings.hasToken}
                >
                  清除 Token
                </Button>
              </Stack>

              {settingsError && <Alert severity="error">{settingsError}</Alert>}
              {settingsFeedback && <Alert severity="success">{settingsFeedback}</Alert>}
            </Stack>
          </Stack>
        </DialogContent>
      </Dialog>

      <Dialog open={showTextInputDialog && !isPetMode} onClose={closeTextInputDialog} maxWidth="sm" fullWidth>
        <DialogTitle>发送文字消息</DialogTitle>
        <DialogContent>
          <Stack spacing={2} sx={{ pt: 1 }}>
            <TextField
              value={textInputContent}
              onChange={(event) => setTextInputContent(event.target.value)}
              multiline
              minRows={3}
              maxRows={8}
              placeholder="输入你想让她说的话..."
              disabled={isStreaming}
              inputProps={{ maxLength: 400 }}
              onKeyDown={(event) => {
                if (event.key === 'Enter' && !event.shiftKey) {
                  event.preventDefault();
                  void submitTextInput();
                }
              }}
            />
            {textInputError && (
              <Box sx={{ color: 'error.main', fontSize: 14, lineHeight: 1.5 }}>{textInputError}</Box>
            )}
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button variant="text" onClick={closeTextInputDialog} disabled={isStreaming}>
            取消
          </Button>
          <Button variant="contained" onClick={() => void submitTextInput()} disabled={isStreaming}>
            {isStreaming ? '发送中' : '发送'}
          </Button>
          <Button variant="text" color="warning" onClick={stopStreaming} disabled={!isStreaming}>
            停止流式
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}
